on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-20.04, macos-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller -w main.py
    # Optionally verify that it works (provided that it does not need user interaction)
    # - run: ./dist/your-code/your-code
    - uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }} Build
        path: dist/*
